/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Newsletter service. Represents a row in the &quot;Newsletter_Newsletter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.newsletter.model.impl.NewsletterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.newsletter.model.impl.NewsletterImpl</code>.
 * </p>
 *
 * @author Charles Pederson
 * @see Newsletter
 * @generated
 */
@ProviderType
public interface NewsletterModel extends BaseModel<Newsletter> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletter model instance should use the {@link Newsletter} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletter.
	 *
	 * @return the primary key of this newsletter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletter.
	 *
	 * @param primaryKey the primary key of this newsletter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the newsletter ID of this newsletter.
	 *
	 * @return the newsletter ID of this newsletter
	 */
	public long getNewsletterId();

	/**
	 * Sets the newsletter ID of this newsletter.
	 *
	 * @param newsletterId the newsletter ID of this newsletter
	 */
	public void setNewsletterId(long newsletterId);

	/**
	 * Returns the issue ID of this newsletter.
	 *
	 * @return the issue ID of this newsletter
	 */
	public long getIssueId();

	/**
	 * Sets the issue ID of this newsletter.
	 *
	 * @param issueId the issue ID of this newsletter
	 */
	public void setIssueId(long issueId);

	/**
	 * Returns the title of this newsletter.
	 *
	 * @return the title of this newsletter
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletter.
	 *
	 * @param title the title of this newsletter
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this newsletter.
	 *
	 * @return the author of this newsletter
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this newsletter.
	 *
	 * @param author the author of this newsletter
	 */
	public void setAuthor(String author);

	/**
	 * Returns the order of this newsletter.
	 *
	 * @return the order of this newsletter
	 */
	public int getOrder();

	/**
	 * Sets the order of this newsletter.
	 *
	 * @param order the order of this newsletter
	 */
	public void setOrder(int order);

	/**
	 * Returns the content of this newsletter.
	 *
	 * @return the content of this newsletter
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this newsletter.
	 *
	 * @param content the content of this newsletter
	 */
	public void setContent(String content);

}